# Generated by Django 5.0.1 on 2024-11-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TumorPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tumor_images/')),
                ('predicted_class', models.CharField(choices=[('glioma', 'Glioma Tumor'), ('meningioma', 'Meningioma Tumor'), ('no_tumor', 'No Tumor'), ('pituitary', 'Pituitary Tumor')], max_length=20)),
                ('confidence_score', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
